<Project>
  <PropertyGroup Label="Package metadata" Condition="'$(IsPackable)' != 'false'">
    <Product>X.Web.Lockout</Product>
    <Description>User account lockout functionality built on top of ASP.NET Core Identity.</Description>
    <PackageId>X.Web.Lockout</PackageId>
    <PackageTags>aspnetcore;identity;lockout;security;authentication</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/a-gubskiy/X.Web.Lockout</PackageProjectUrl>
    <RepositoryUrl>https://github.com/a-gubskiy/X.Web.Lockout</RepositoryUrl>
    <PackageIcon>x-web.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
